### ISSUE TITLE
app启动不了报错

### ISSUE THREAD

**Issue by Laughing88** [wuba/taro-playground#18]
error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening taroDemo.xcworkspace

**Comment by zhiqingchen** [comment]
先用下自己的签名文件，这块我们改一下

**Comment by zhiqingchen** [comment]
https://github.com/wuba/taro-playground/issues/20
重复issue
