### ISSUE TITLE
Android端APP启动报错  密码错误 希望修改

### ISSUE THREAD

**Issue by Laughing88** [wuba/taro-playground#19]
Execution failed for task ':app:packageDebug'.
> A failure occurred while executing com.android.build.gradle.tasks.PackageAndroidArtifact$IncrementalSplitterRunnable
   > com.android.ide.common.signing.KeytoolException: Failed to read key androiddebugkey from store "/Volumes/project/个人项目/taro/taro-playground/android/app/debug.keystore": keystore password was incorrect

**Comment by zhiqingchen** [comment]
bug，待修复。
可以先用下自己的签名文件。

**Comment by zhiqingchen** [comment]
https://developer.android.com/studio/publish/app-signing

**Comment by Laughing88** [comment]
请尽快修复一下：
![image](https://user-images.githubusercontent.com/56735757/143578116-77220081-b93e-42b5-98c2-89849f35a2e2.png)
