### ISSUE TITLE
启用 Hermes

### ISSUE THREAD

**Issue by zhiqingchen** [wuba/taro-playground#26]
### 文档

https://reactnative.dev/docs/hermes

### 问题
- Taro RN 在编译时，没有使用 `react-native/scripts/react-native-xcode.sh` 和 `node_modules/react-native/react.gradle`
以至于没有进行字节码的打包，相关内容需要进行重构
- 入口文件通过 --entry-file 传入 node_modules/metro/src/node-haste/DependencyGraph/assets/empty-module.js

**Comment by charlzyx** [comment]
WIP: 补充一点东西: for Android
根据这里 [Bundling React Native during Android release builds](https://proandroiddev.com/bundling-react-native-during-android-release-builds-ec52c24e200d)
的这一段注释, 可以知道, 默认情况下, debug 模式不会开启asset, 同时, Taro 的asset 是通过 runner 中的metro bundler 做的, 也就是说, 需要来消化一下 node_modules/react-native/react.gradle 这个货来改造为 hermes 打包

```gradle
/**
 * The react.gradle file registers a task for each build variant (e.g. bundleDebugJsAndAssets
 * and bundleReleaseJsAndAssets).
 * These basically call `react-native bundle` with the correct arguments during the Android build
 * cycle. By default, bundleDebugJsAndAssets is skipped, as in debug/dev mode we prefer to load the
 * bundle directly from the development server. Below you can see all the possible configurations
 * and their defaults. If you decide to add a configuration block, make sure to add it before the
 * `apply from: "../../node_modules/react-native/react.gradle"` line.
 *
 * project.ext.react = [
 *   // the name of the generated asset file containing your JS bundle
 *   bundleAssetName: "index.android.bundle",
 *
 *   // the entry file for bundle generation
 *   entryFile: "index.android.js",
 *
 *   // whether to bundle JS and assets in debug mode
 *   bundleInDebug: false,
.
.
.
*/
```

**Comment by snice** [comment]
1.8.0开始已经默认用hermes了吧

**Comment by zhiqingchen** [comment]
是的，Hermes可自行开启或关闭，使用方案与 RN 一致，
