### ISSUE TITLE
app中的示例页面间跳转显示错乱

### ISSUE THREAD

**Issue by ihwf** [wuba/taro-playground#36]
安卓端，页面间跳转内容错乱
![Screenshot_20220112_230138_com playground taro](https://user-images.githubusercontent.com/17941662/149165375-68e3cbd6-ac4d-4847-b471-3a4847b2463d.jpg)
![Screenshot_20220112_230110_com playground taro](https://user-images.githubusercontent.com/17941662/149165452-dfb2304a-3371-40e7-8dc9-45de0cd058e0.jpg)
![Screenshot_20220112_230035_com playground taro](https://user-images.githubusercontent.com/17941662/149165471-e822a3d4-55f4-4da2-a92c-dd94d16d5eaf.jpg)

**Comment by zhiqingchen** [comment]
手机型号？
对应的app版本号？

**Comment by ihwf** [comment]
测试了华为 mate20 Pro和华为 p40 pro,结果一样, harmony 2, Android10, APP 版本 Taro 3.3.19, RN 0.66.4, Taro Playground 1.3.6 , 这个是录屏 [录屏]( https://www.aliyundrive.com/s/DnfwuV1w1db)

**Comment by zhiqingchen** [comment]
相关问题
https://github.com/react-navigation/react-navigation/issues/8912

**Comment by zhiqingchen** [comment]
已修复，待新版本发布
