### ISSUE TITLE
这个项目是不支持小程序查看吗？

### ISSUE THREAD

**Issue by wjkang** [wuba/taro-playground#53]
运行 yarn dev:weapp 后报错：

./node_modules/@react-native-community/cameraroll/js/CameraRoll.js
Module build failed (from ./node_modules/@tarojs/mini-runner/node_modules/babel-loader/lib/index.js):
SyntaxError: /Users/ruoxie/Github/taro-playground/node_modules/@react-native-community/cameraroll/js/CameraRoll.js: Support for the experimental syntax 'flow' isn't currently enabled (32:8):

  30 | };
  31 |
> 32 | export type GroupTypes = $Keys<typeof GROUP_TYPES_OPTIONS>;
     |        ^
  33 |
  34 | export type Include =
  35 |   | 'filename'

Add @babel/preset-flow (https://git.io/JfeDn) to the 'presets' section of your Babel config to enable transformation.
If you want to leave it as-is, add @babel/plugin-syntax-flow (https://git.io/vb4yb) to the 'plugins' section to enable parsing.

**Comment by zhiqingchen** [comment]
不支持

**Comment by zhiqingchen** [comment]
要兼容小程序，还需要做些处理

**Comment by zhiqingchen** [comment]
最新已支持
