### ISSUE TITLE
拉取代码编译安卓app报错

### ISSUE THREAD

**Issue by zhaihongbin** [wuba/taro-playground#78]
> Task :expo:compileDebugKotlin FAILED
 \node_modules\expo\android\src\main\java\expo\modules\ReactNativeHostWrapperBase.kt: (50, 3): 'getUIImplementationProvider' overrides nothing
 \node_modules\expo\android\src\main\java\expo\modules\ReactNativeHostWrapperBase.kt: (50, 76): Unresolved reference: UIImplementationProvider
 \node_modules\expo\android\src\main\java\expo\modules\ReactNativeHostWrapperBase.kt: (51, 12): Not enough information to infer type variable T
请问这是和我本机开发环境有关吗

**Comment by 4332weizi** [comment]
哪个分支？

**Comment by zhaihongbin** [comment]
> 

https://github.com/wuba/taro-playground/tree/releases/v1.8.0

**Comment by zhiqingchen** [comment]
https://github.com/infinitered/ignite/pull/2296/files
需要升级下 rn 和 expo 版本

**Comment by zhiqingchen** [comment]
已修复，更新下代码
