### ISSUE TITLE
taro-playground-1.4.8在11月4日rn官方bug之后发布Android失败

### ISSUE THREAD

**Issue by qq33923881** [wuba/taro-playground#80]
**相关平台**
React Native

**使用框架**
React

**环境信息**
windows7
jdk8
gradle6.9
nodejs: v12.22.11
taro:  v3.4.10

**复现步骤**
下载并解压 taro-playground-1.4.8
yarn upgradePeerdeps
yarn build:rn --platform android
cd android
gradlew assembleRelease

**结果**
发布apk失败(如下)

FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:checkReleaseAarMetadata'.
> Multiple task action failures occurred:
   > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
      > The minCompileSdk (31) specified in a
        dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
        is greater than this module's compileSdkVersion (android-30).
        Dependency: androidx appcompat:appcompat:1.4.1
AAR metadata file: C:\Users\Administrator\.gradle\caches\transforms-3\3a0feba48fed99a23f9c4bbf34263afa\transforms\appcompat:1.4.1\META-INF\com\android\build\gradle\arr-metadata.properties

**尝试解决**
删除node_modules
修改 package.json的 "react-native": "0.67.5",
yarn upgradePeerdeps
yarn build:rn --platform android
cd android
gradlew assembleRelease
结果还是发布失败

**Comment by zhiqingchen** [comment]
升级 react native + expo + https://github.com/facebook/react-native/issues/35210#issuecomment-1304536693
