### ISSUE TITLE
Taro 3.6.0不支持

### ISSUE THREAD

**Issue by dicklwm** [wuba/taro-playground#85]
使用Taro App@1.7.4、@1.8.0.x
都会报错误

 LOG  Running "taroDemo" with {"rootTag":11}
 ERROR  Invariant Violation: "taroDemo" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes

望尽快支持Taro 3.6.0

或者还有没有别的什么调试方式，不需要降Taro版本的？

**Comment by zhiqingchen** [comment]
1.7.x 不支持 taro 3.6，请等 1.8.x 发布

**Comment by snice** [comment]
taro@3.6.1 创建rn项目（taro init，react native模板）
使用taro-playground 1.8.0 release.apk 扫码依旧提示这个错误

**Comment by zhiqingchen** [comment]
检查appName，是否为taroDemo

**Comment by snice** [comment]
> 

是的

**Comment by snice** [comment]
> 检查appName，是否为taroDemo

是的

**Comment by snice** [comment]
taro init test，也报这个错误

**Comment by snice** [comment]
> taro init test，也报这个错误

ios测试了下，也报这个错误
