### ISSUE TITLE
yarn ios在iphone14 simulator中打不开

### ISSUE THREAD

**Issue by Hao-yiwen** [wuba/taro-playground#91]
能否在readme中补充一下具体的node、xcode版本
xcode版本是14.3.1

**Comment by zhiqingchen** [comment]
都是用的最新版运行的吗

**Comment by zhiqingchen** [comment]
参考
https://github.com/wuba/taro-playground/blob/main/.github/workflows/assemble_ios_release.yml

https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md

**Comment by Hao-yiwen** [comment]
macos14+xcode14 能升级一下吗 不然本地都没法预览了

**Comment by zhiqingchen** [comment]
macos 14 github action 还未支持

**Comment by Hao-yiwen** [comment]
那你们本地开发用13吗

**Comment by Hao-yiwen** [comment]
<img width="671" alt="image" src="https://github.com/wuba/taro-playground/assets/42827938/c152ef13-4a4d-45ee-88ef-688839b7b2dc">
感觉pods这块依赖有问题，需要适配一下
