### ISSUE TITLE
ios本地构建失败 麻烦管理员有时间更新一下podfile.lock和yarn.lock 新版本xcode始终有问题

### ISSUE THREAD

**Issue by Hao-yiwen** [wuba/taro-playground#99]
<img width="1142" alt="image" src="https://github.com/wuba/taro-playground/assets/42827938/914b1775-b891-4433-a444-2dd16799ccf3">

**Comment by Hao-yiwen** [comment]
本地选择最小构建版本15.0或13.0 都试过了

**Comment by Hao-yiwen** [comment]
升级后也尝试过了 虽然构建没问题 但是打开后又会有依赖问题

**Comment by Hao-yiwen** [comment]
升级依赖版本也尝试过了 例如将0.70.7升级到0.70.13 虽然构建成功了 但是进入页面后就会有依赖问题 难顶

**Comment by Hao-yiwen** [comment]
经过一些列努力 终于在macos15中成功启动了项目
![image](https://github.com/wuba/taro-playground/assets/42827938/354d450e-65e6-4185-bfdc-b99bb5b2ac3b)
但是目前依赖问题确实有点大 请管理员有时间修复一下
前面贴图的解决方案在这里[解决方案](https://github.com/facebook/react-native/issues/34106)

**Comment by Hao-yiwen** [comment]
https://github.com/facebook/react-native/issues/34106

**Comment by zhiqingchen** [comment]
感谢
请问解决方案指的是这个吗？
  ...
  post_install do |installer|
    react_native_post_install(
      installer,
      # Set `mac_catalyst_enabled` to `true` in order to apply patches
      # necessary for Mac Catalyst builds
      :mac_catalyst_enabled => false
    )
    # NOTE: Change IPHONEOS_DEPLOYMENT_TARGET to 12.4.
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.4'
      end
    end
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end

**Comment by Hao-yiwen** [comment]
是的

**Comment by zhiqingchen** [comment]
已更新并验证
